# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

        run: |
         npm i
         npm run build 
         git config --global user.email "chernetsova.tatya@gmail.com"
         git config --global user.name "Чернецова Татьяна"
         git config --global credential.helper wincred
         npm run deploy
       
       # Deploy  
      # name: Deploy
      # uses: peaceiris/actions-gh-pages@v3
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
      #   publish_dir: ./dist
